import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layout/Navbar";
import { pinkAverage } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`min-h-full flex flex-col ${pinkAverage.className}`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
